### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mattmassicotte** [Frizlab/FSEventsWrapper#5]
I think it would be a great idea to add a license to the project. I'm a fan of the BSD-3 clause, but MIT is popular. Ultimately, it's up to you. If you go GPL, please just make sure you're doing it intentionally.

**Comment by Frizlab** [comment]
I'll add the MIT license ASAP.
Most of my projects have the MIT license (Apache 2 for projects from `happn-app`); I just forgot for this one (it was one of my first open-source projects!)
